# YAML
main:
  logging_level: INFO #['NOTSET', 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']
  numpy_print_precision: 2
  use_ROS: False # True if any robot is in the real world
  ROS_node_name: 'Python_Node'
  max run time: 400 # number of frames (-1 for infinite run time)
  log_time: False
  headless_mode: False
  playback_rosbags: 
      # Test 4: 'test4.bag'

data_logging:
  record_data: 
    robot positions: all
    grid probability: 2D #2D or 4D 
    questions: True
    answers: True

cops:
  Deckard:
    pose: [0, 0, 90]  # [x(meters), y(meters), theta(degrees)]
    robber_model: static  # ['static','clockwise','counterclockwise','random walk']
    pose_source: python  # ['python' or a ros topic string like '/deckard/odom']
    web_interface_topic: python # python or rostopic name
    other_robot_names: 
      robbers: ['Roy']  #['Roy', 'Pris']
      distractors: []  #['Zhora']
    mission_planner_cfg:
      target_order: ['Roy']  #['Roy', 'Pris']
    goal_planner_cfg:
      type_: MAP  # ['stationary', 'simple', 'trajectory', 'particle', 'MAP']
    path_planner_cfg:
      type_: 'a_star'  # ['direct', 'a_star'] 
    camera_cfg:
      max_view_dist: 1.0
      min_view_dist: 0.0
    map_cfg:
      plot_robbers: True # True for all, False for none, or list of robbers to plot
      map_name: fleming
      combined_only: False
      publish_to_ROS: False
    human_cfg:
      false_alarm_prob: 0.2  # probability human will answer a question correctly
      web_interface_topic: python  # ['python' or a rostopic name ('human_sensor')]
    questioner_cfg:
      use_ROS: False
      auto_answer: True
      # human_answer_chance: 0.9  # probability human will answer a question
      target_order: ['Roy']  # ['Pris', 'Roy']
      target_weights: [1] #[11, 10]
      repeat_annoyance: 0.8  # max penalty to a repeated question
      repeat_time_penalty: 300  # seconds during which a repeat question is penalized
      ask_every_n: 5 # nonpositive number to turn off
      n_lookahead_steps: 2  # number of questions for non-myopic VOI
      minimize_questions: True  # ask over a smaller set of questions

robbers:
  Roy:
    pose_source: python  # ['python' or a ros topic string like '/roy/odom']
    goal_planner_cfg:
      type_: simple  # ['stationary', 'simple', 'trajectory']
    path_planner_cfg:
      type_: 'a_star'  # ['direct', 'a_star'] 

distractors:

human_interface:
  measurement_types:
    velocity: False
    area: True
    object: True
