# YAML
main:
  logging_level: INFO  #['NOTSET', 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']
  numpy_print_precision: 2
  use_ROS: True # True if any robot is in the real world
  ROS_node_name: 'Python_Node'
  max_run_time: 10  # in seconds, -1 for infinite
  log_time: False

cops:
  Deckard:
    pose: [0, 0, 90]  # [x(meters), y(meters), theta(degrees)]
    robber_model: static  # ['static','clockwise','counterclockwise','random walk']
    pose_source: tf  # ['python' or a ros topic string like '/deckard/odom']
    web_interface_topic: human_sensor # python or rostopic name
    other_robot_names: 
      robbers: ['Roy', 'Zhora']
      distractors: ['Pris']
    mission_planner_cfg:
      target_order: ['Roy', 'Zhora']
    goal_planner_cfg:
      type_: MAP  # ['stationary', 'simple', 'trajectory', 'particle', 'MAP']
    path_planner_cfg:
      type_: 'direct'  # ['direct', 'a_star'] 
    camera_cfg:
      max_view_dist: 1.0
      min_view_dist: 0.3
    map_cfg:
      plot_robbers: True #True for all, False for none, or list of robbers to plot
      map_name: fleming
      combined_only: False
    questioner_cfg:
      target_order: ['Zhora', 'Roy']
      false_alarm_prob: 0.1
      use_ROS: True


robbers:
  Roy:
    pose_source: tf  # ['python' or a ros topic string like '/roy/odom']
    goal_planner_cfg:
      type_: stationary  # ['stationary', 'simple', 'trajectory']
    path_planner_cfg:
      type_: 'direct'  # ['direct', 'a_star'] 
  Zhora:
    pose_source: tf  # ['python' or a ros topic string like '/zhora/odom']
    goal_planner_cfg:
      type_: stationary  # ['stationary', 'simple', 'trajectory']
    path_planner_cfg:
      type_: 'direct'  # ['direct', 'a_star'] 

distractors:
  Pris:
    pose_source: tf  # ['python' or a ros topic string like '/pris/odom']
    goal_planner_cfg:
      type_: stationary  # ['stationary', 'simple', 'trajectory']
    path_planner_cfg:
      type_: 'direct'  # ['direct', 'a_star'] 

human_interface:
  measurement_types:
    velocity: False
    area: True
    object: True
